import {
  Receipt,
  CreditCard,
  Printer,
  SplitSquareHorizontal,
  WifiOff,
  Package,
  Bell,
  ClipboardCheck,
  Truck,
  Globe,
  Rss,
  CheckCircle2,
  RefreshCw,
  BarChart3,
  FileSpreadsheet,
  MessageSquareText,
  ShieldAlert,
  ClipboardList,
  Tags,
  Image as ImageIcon,
  LayoutGrid,
  Heart,
  UserPlus,
  History,
  Star,
} from 'lucide-react'
import { BillingMockup, InventoryMockup, ReportsMockup, OrderingMockup, MenuMockup, CrmMockup } from './mockups'
import type { FeaturePageConfig } from './feature-page-types'

export const FEATURE_PAGES: FeaturePageConfig[] = [
  {
    slug: 'billing',
    navLabel: 'Billing & POS',
    eyebrow: 'Billing & POS',
    headline: 'Restaurant billing that keeps up, even at 9 PM on a Friday.',
    subheadline:
      'Punch orders, generate KOTs, split or merge bills, and take payment — every screen built to load in under 1.5 seconds, with billing that keeps working for up to 72 hours offline.',
    visual: <BillingMockup />,
    capabilities: [
      { icon: CreditCard, title: 'Multi-payment billing', desc: 'UPI, cards, and cash — reconciled automatically into your daily sales report.' },
      { icon: Printer, title: 'Any printer, any KOT', desc: 'Thermal, Bluetooth, and LAN printers you already own — station-wise routing included.' },
      { icon: SplitSquareHorizontal, title: 'Split & merge bills', desc: 'Multi-table, multi-guest billing without breaking your billing flow.' },
      { icon: WifiOff, title: '72-hour offline mode', desc: 'Billing and KOT printing keep working when the internet drops, and sync automatically after.' },
    ],
    highlights: [
      'Works with the printers and tablets you already own',
      'Runs on Android, Windows, and the web — no proprietary terminal',
      'GST-compliant invoices with CGST/SGST auto-calculated',
      'Discounts, coupons, and service charge applied without leaving the billing screen',
    ],
    stats: [
      { value: '< 1.5s', label: 'Target screen load time' },
      { value: '72 hrs', label: 'Offline billing window' },
      { value: '0', label: 'Proprietary hardware required' },
    ],
    faqs: [
      { q: 'Do I need to buy new hardware?', a: 'No. Atlas works with the printers, tablets, and Android devices you already own — no proprietary hardware lock-in.' },
      { q: 'What happens if my internet goes down?', a: 'Billing, KOT printing, and order-taking keep working for up to 72 hours offline. Everything syncs automatically once you\'re back online.' },
      { q: 'Can I split or merge bills across tables?', a: 'Yes — split by item, by guest, or merge multiple tables into one bill, directly from the billing screen.' },
      { q: 'Is GST calculated automatically?', a: 'Yes — CGST and SGST are calculated per item based on the tax rates you configure during setup.' },
    ],
  },
  {
    slug: 'inventory',
    navLabel: 'Inventory',
    eyebrow: 'Inventory Management',
    headline: 'Inventory that updates itself.',
    subheadline:
      'Recipe-based auto deduction, low-stock WhatsApp alerts, and day-end reports — so nothing runs out mid-service and nothing walks out the back door unnoticed.',
    visual: <InventoryMockup />,
    capabilities: [
      { icon: Package, title: 'Recipe-based auto deduction', desc: 'Stock updates itself the moment an order is billed — no manual stock entry.' },
      { icon: Bell, title: 'Low-stock WhatsApp alerts', desc: 'Get notified the moment an ingredient crosses your threshold, before it runs out.' },
      { icon: ShieldAlert, title: 'Wastage tracking', desc: 'Log spoilage and wastage separately from sales consumption for an accurate cost picture.' },
      { icon: ClipboardCheck, title: 'GRN & purchase entry', desc: 'Record goods received and purchase orders directly against your supplier list.' },
    ],
    highlights: [
      'Day-end inventory reports, generated automatically',
      'Item-wise consumption tracking tied to your recipes',
      'Supplier and purchase history in one place',
      'Works alongside your existing stock-taking process',
    ],
    stats: [
      { value: 'Auto', label: 'Recipe-based stock deduction' },
      { value: 'WhatsApp', label: 'Low-stock alerts delivered' },
      { value: 'Day-end', label: 'Inventory reports, automated' },
    ],
    faqs: [
      { q: 'Does inventory update automatically when I bill an order?', a: 'Yes — recipe-based deduction reduces raw material stock the moment an order is billed, based on the recipe you set up for each menu item.' },
      { q: 'How do low-stock alerts work?', a: 'You set a threshold per item; when stock crosses it, an alert goes straight to your WhatsApp — no need to check a dashboard.' },
      { q: 'Can I track wastage separately from sales?', a: 'Yes — wastage and spoilage are logged separately so your consumption reports reflect what was actually sold.' },
      { q: 'Can I manage inventory across multiple outlets?', a: 'Multi-outlet stock transfer and central kitchen coordination are on our roadmap — today, inventory is managed per outlet.' },
    ],
  },
  {
    slug: 'online-ordering',
    navLabel: 'Online Ordering',
    eyebrow: 'Online Ordering',
    headline: 'Every channel. One queue.',
    subheadline:
      'Zomato and Swiggy orders sync directly into your order queue alongside dine-in and takeaway — no re-typing, no separate tablet to babysit.',
    visual: <OrderingMockup />,
    capabilities: [
      { icon: Globe, title: 'Unified order queue', desc: 'Every channel — dine-in, takeaway, Zomato, Swiggy — lands in the same screen.' },
      { icon: Rss, title: 'Zomato & Swiggy sync', desc: 'Orders sync directly into Atlas — no manual entry, no missed orders.' },
      { icon: CheckCircle2, title: 'Mark-ready sync', desc: 'Mark an order ready once, and the status updates on the aggregator app too.' },
      { icon: RefreshCw, title: 'Order reconciliation', desc: 'Match aggregator payouts against orders automatically at day-end.' },
    ],
    highlights: [
      'No separate tablet needed per aggregator',
      'Kitchen sees online orders in the same KDS queue as dine-in',
      'Order status stays in sync across every channel',
      'Built to add more aggregators as Atlas grows',
    ],
    stats: [
      { value: '2', label: 'Aggregators synced at launch' },
      { value: '1', label: 'Unified queue for every channel' },
      { value: '0', label: 'Manual re-entry needed' },
    ],
    faqs: [
      { q: 'Which aggregators does Atlas support today?', a: 'Zomato and Swiggy orders sync directly into your order queue. More aggregator integrations are planned as Atlas grows.' },
      { q: 'Do I need a separate tablet for each aggregator?', a: 'No — every channel lands in the same unified queue as your dine-in and takeaway orders.' },
      { q: 'Does the kitchen see online orders too?', a: 'Yes — online orders route into the same KDS queue as every other order, with the source clearly tagged.' },
      { q: 'How does payment reconciliation work?', a: 'Aggregator payouts are matched against your order records automatically, so you can spot discrepancies at day-end.' },
    ],
  },
  {
    slug: 'reports',
    navLabel: 'Reports & Analytics',
    eyebrow: 'Reports & Analytics',
    headline: 'Reports that write themselves.',
    subheadline:
      '12 core reports covering sales, GST, staff activity, and item-wise profitability — updated live, exportable for Tally, and summarized to your WhatsApp every night.',
    visual: <ReportsMockup />,
    capabilities: [
      { icon: BarChart3, title: 'Live sales & GST reports', desc: 'Day-end sales, hourly trends, and GST breakup — always current, never stale.' },
      { icon: MessageSquareText, title: 'WhatsApp nightly summary', desc: 'Your day\'s numbers land in your WhatsApp automatically — no dashboard required.' },
      { icon: FileSpreadsheet, title: 'P&L snapshot & GSTR-1 export', desc: 'Export straight into the format your accountant or Tally already expects.' },
      { icon: ShieldAlert, title: 'Void & staff activity reports', desc: 'See every void, discount, and cancellation with who approved it and why.' },
    ],
    highlights: [
      '12 core reports included — no add-on required',
      'Exportable for Tally and GSTR-1 filing',
      'Item-wise profitability, not just top-line sales',
      'Reports update in real time as orders come in',
    ],
    stats: [
      { value: '12', label: 'Core reports included' },
      { value: 'Nightly', label: 'WhatsApp summary delivery' },
      { value: 'GSTR-1', label: 'Export-ready format' },
    ],
    faqs: [
      { q: 'What reports come included?', a: '12 core reports covering daily sales, hourly trends, discounts, voids, cash reconciliation, GST, and item-wise profitability — none of them are paid add-ons.' },
      { q: 'How does the WhatsApp nightly summary work?', a: 'Every night, a summary of your day\'s sales, orders, and best sellers is sent automatically to your WhatsApp — no login required to see how the day went.' },
      { q: 'Can I export reports for my accountant?', a: 'Yes — reports export in a Tally-compatible format, and GSTR-1 export is built in.' },
      { q: 'Can I see which staff member approved a void or discount?', a: 'Yes — every void, discount, and cancellation is logged against the staff member who actioned it.' },
    ],
  },
  {
    slug: 'menu',
    navLabel: 'Menu Management',
    eyebrow: 'Menu Management',
    headline: 'Update your menu once. It\'s everywhere.',
    subheadline:
      'Categories, variations, add-ons, and pricing — manage your entire menu from one screen, and see the change reflected instantly on billing and KDS.',
    visual: <MenuMockup />,
    capabilities: [
      { icon: ClipboardList, title: 'Digital menu builder', desc: 'Categories, items, and descriptions — organized the way your restaurant actually runs.' },
      { icon: Tags, title: 'Variations & add-ons', desc: 'Size, spice level, extra toppings — priced independently per variation.' },
      { icon: LayoutGrid, title: 'Area-wise menus', desc: 'Different menus for dine-in, delivery, or a separate bar menu, from the same system.' },
      { icon: ImageIcon, title: 'Bulk Excel import', desc: 'Import your entire existing menu from a spreadsheet instead of typing it item by item.' },
    ],
    highlights: [
      'Menu changes reflect instantly on billing and KDS',
      'Mark items unavailable in seconds during a stockout',
      'Up to 500 menu items supported',
      'Category-wise organization matches how your kitchen thinks',
    ],
    stats: [
      { value: 'Bulk', label: 'Excel import supported' },
      { value: '500', label: 'Menu items supported' },
      { value: 'Live', label: 'Sync across billing & KDS' },
    ],
    faqs: [
      { q: 'Can I import my existing menu?', a: 'Yes — import via Excel/CSV, or add items manually one at a time. Our onboarding team can help with the initial import.' },
      { q: 'Can I set up different menus for dine-in vs. delivery?', a: 'Yes — you can configure area-specific or channel-specific menus from the same system.' },
      { q: 'How do item variations and add-ons work?', a: 'Each item can have variations (e.g. size, spice level) and add-ons, each priced independently.' },
      { q: 'What happens when an item runs out mid-service?', a: 'Mark it unavailable in a couple of taps — it disappears from billing and KDS instantly.' },
    ],
  },
  {
    slug: 'crm',
    navLabel: 'CRM & Loyalty',
    eyebrow: 'CRM & Loyalty',
    headline: 'Know your regulars. Keep them coming back.',
    subheadline:
      'Every order builds a customer profile automatically — visit history, spend, and preferences — with no separate CRM system to maintain.',
    visual: <CrmMockup />,
    capabilities: [
      { icon: UserPlus, title: 'Automatic customer capture', desc: 'Every order builds a profile — no separate sign-up flow required.' },
      { icon: History, title: 'Order history & visit tracking', desc: 'See how often a customer visits, what they order, and how much they spend.' },
      { icon: Heart, title: 'Feedback collection', desc: 'Capture feedback right after a visit, tied to the specific order.' },
      { icon: Star, title: 'Segment-ready profiles', desc: 'Customer data structured for segmentation — ready for campaigns as your loyalty program grows.' },
    ],
    highlights: [
      'No separate CRM system or spreadsheet to maintain',
      'Customer profiles build automatically from every order',
      'Feedback tied directly to the order that generated it',
      'Foundation in place for loyalty and campaigns as you grow',
    ],
    stats: [
      { value: 'Auto', label: 'Customer capture from every order' },
      { value: '0', label: 'Extra setup required' },
      { value: '100%', label: 'Order history retained' },
    ],
    faqs: [
      { q: 'Do customers need to sign up for anything?', a: 'No — a profile is created automatically from their order details, with no separate sign-up flow needed.' },
      { q: 'Can I see a customer\'s order history?', a: 'Yes — every visit, order, and spend amount is tracked against their profile automatically.' },
      { q: 'Does Atlas support loyalty points or SMS campaigns?', a: 'Customer data is structured and ready for segmentation today; loyalty points and campaign tools are on our roadmap.' },
      { q: 'How is feedback collected?', a: 'Feedback can be collected right after a visit and is tied directly to the order it relates to.' },
    ],
  },
]
